import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PageMargin from "@/components/PageMargin";
import Link from "next/link";
import Provider from "@/components/providers/Provider";
import NavLink from "@/components/NavLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Provider>
          <nav className="border h-20">
            <PageMargin className="flex items-center h-full gap-8">
              <NavLink href="/" exact>
                Home
              </NavLink>
              <NavLink href="/users">Users</NavLink>
              <NavLink href="/auth">Auth</NavLink>
            </PageMargin>
          </nav>
          <PageMargin>{children}</PageMargin>
        </Provider>
      </body>
    </html>
  );
}
