import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Provider from "@/components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <nav className="w-full flex gap-16 p-4 justify-center border-b-2 border-slate-300">
            <Link href="/">Home</Link>
            <Link href="/drinks">Drinks</Link>
            <Link href="/food">Food</Link>
          </nav>
          <div className="p-4">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
